[package]
name = "babeltrace2-sys"
version = "0.2.0"
authors = ["Jon Lamb <jon@auxon.io>"]
edition = "2018"
build = "build.rs"
links = "babeltrace2"
description = "Rust sys crate for babeltrace2"
homepage = "https://babeltrace.org/"
license = "MIT"

[build-dependencies]
autotools = "0.2"
pkg-config = "0.3"
bindgen = "0.53"

[dependencies]
log = "0.4"
err-derive = "0.3"
uuid = { version = "0.8", features = ["v5"] }
ordered-float = "2.2.0"

[dev-dependencies]
structopt = "0.3"
ctrlc = "3.2"
env_logger = "0.8"
url = "2.1"
